# coding: utf-8

"""
    Open API Specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.representatives_get_page_parameter_any_of1 import RepresentativesGetPageParameterAnyOf1

class TestRepresentativesGetPageParameterAnyOf1(unittest.TestCase):
    """RepresentativesGetPageParameterAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepresentativesGetPageParameterAnyOf1:
        """Test RepresentativesGetPageParameterAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepresentativesGetPageParameterAnyOf1`
        """
        model = RepresentativesGetPageParameterAnyOf1()
        if include_optional:
            return RepresentativesGetPageParameterAnyOf1(
                count = True,
                limit = 1,
                offset = 0
            )
        else:
            return RepresentativesGetPageParameterAnyOf1(
        )
        """

    def testRepresentativesGetPageParameterAnyOf1(self):
        """Test RepresentativesGetPageParameterAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
