# coding: utf-8

"""
    Open API Specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.representatives_get_page_parameter import RepresentativesGetPageParameter

class TestRepresentativesGetPageParameter(unittest.TestCase):
    """RepresentativesGetPageParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepresentativesGetPageParameter:
        """Test RepresentativesGetPageParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepresentativesGetPageParameter`
        """
        model = RepresentativesGetPageParameter()
        if include_optional:
            return RepresentativesGetPageParameter(
                after = '',
                before = '',
                count = True,
                limit = 1,
                offset = 0
            )
        else:
            return RepresentativesGetPageParameter(
        )
        """

    def testRepresentativesGetPageParameter(self):
        """Test RepresentativesGetPageParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
