# coding: utf-8

"""
    Open API Specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.representative_api import RepresentativeApi


class TestRepresentativeApi(unittest.TestCase):
    """RepresentativeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RepresentativeApi()

    def tearDown(self) -> None:
        pass

    def test_representatives_get(self) -> None:
        """Test case for representatives_get

        """
        pass

    def test_representatives_id_get(self) -> None:
        """Test case for representatives_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
