# coding: utf-8

"""
    Open API Specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ticket import Ticket

class TestTicket(unittest.TestCase):
    """Ticket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ticket:
        """Test Ticket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ticket`
        """
        model = Ticket()
        if include_optional:
            return Ticket(
                attributes = openapi_client.models.ticket_attributes.ticket_attributes(
                    representative_id = '', 
                    subject = '', ),
                id = '',
                relationships = openapi_client.models.ticket_relationships.ticket_relationships(
                    representative = openapi_client.models.ticket_relationships_representative.ticket_relationships_representative(
                        data = [
                            openapi_client.models.ticket_relationships_representative_data_inner.ticket_relationships_representative_data_inner(
                                id = '', 
                                meta = { }, 
                                type = '', )
                            ], ), ),
                type = ''
            )
        else:
            return Ticket(
                id = '',
                type = '',
        )
        """

    def testTicket(self):
        """Test Ticket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
