# coding: utf-8

"""
    Open API Specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tickets_post201_response import TicketsPost201Response

class TestTicketsPost201Response(unittest.TestCase):
    """TicketsPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketsPost201Response:
        """Test TicketsPost201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketsPost201Response`
        """
        model = TicketsPost201Response()
        if include_optional:
            return TicketsPost201Response(
                data = openapi_client.models.ticket.ticket(
                    attributes = openapi_client.models.ticket_attributes.ticket_attributes(
                        representative_id = '', 
                        subject = '', ), 
                    id = '', 
                    relationships = openapi_client.models.ticket_relationships.ticket_relationships(
                        representative = openapi_client.models.ticket_relationships_representative.ticket_relationships_representative(
                            data = [
                                openapi_client.models.ticket_relationships_representative_data_inner.ticket_relationships_representative_data_inner(
                                    id = '', 
                                    meta = { }, 
                                    type = '', )
                                ], ), ), 
                    type = '', ),
                included = [
                    null
                    ],
                meta = { }
            )
        else:
            return TicketsPost201Response(
        )
        """

    def testTicketsPost201Response(self):
        """Test TicketsPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
