# coding: utf-8

"""
    Open API Specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tickets_get200_response import TicketsGet200Response

class TestTicketsGet200Response(unittest.TestCase):
    """TicketsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketsGet200Response:
        """Test TicketsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketsGet200Response`
        """
        model = TicketsGet200Response()
        if include_optional:
            return TicketsGet200Response(
                data = [
                    openapi_client.models.ticket.ticket(
                        attributes = openapi_client.models.ticket_attributes.ticket_attributes(
                            representative_id = '', 
                            subject = '', ), 
                        id = '', 
                        relationships = openapi_client.models.ticket_relationships.ticket_relationships(
                            representative = openapi_client.models.ticket_relationships_representative.ticket_relationships_representative(
                                data = [
                                    openapi_client.models.ticket_relationships_representative_data_inner.ticket_relationships_representative_data_inner(
                                        id = '', 
                                        meta = { }, 
                                        type = '', )
                                    ], ), ), 
                        type = '', )
                    ],
                included = [
                    null
                    ],
                meta = { }
            )
        else:
            return TicketsGet200Response(
        )
        """

    def testTicketsGet200Response(self):
        """Test TicketsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
